from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputLabel.setLineWidth(2)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.button_7 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("7") )
        self.button_7.setGeometry(QtCore.QRect(10, 110, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_7.setFont(font)
        self.button_7.setObjectName("button_7")
        self.button_8 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("8") )
        self.button_8.setGeometry(QtCore.QRect(100, 110, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_8.setFont(font)
        self.button_8.setObjectName("button_8")
        self.button_9 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("9") )
        self.button_9.setGeometry(QtCore.QRect(190, 110, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_9.setFont(font)
        self.button_9.setObjectName("button_9")
        self.button_divide = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("/") )
        self.button_divide.setGeometry(QtCore.QRect(275, 110, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_divide.setFont(font)
        self.button_divide.setObjectName("button_divide")
        self.button_6 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("6") )
        self.button_6.setGeometry(QtCore.QRect(190, 190, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_6.setFont(font)
        self.button_6.setObjectName("button_6")
        self.button_multiply = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("*") )
        self.button_multiply.setGeometry(QtCore.QRect(275, 190, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_multiply.setFont(font)
        self.button_multiply.setObjectName("button_multiply")
        self.button_5 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("5") )
        self.button_5.setGeometry(QtCore.QRect(100, 190, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_5.setFont(font)
        self.button_5.setObjectName("button_5")
        self.button_4 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("4") )
        self.button_4.setGeometry(QtCore.QRect(10, 190, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_4.setFont(font)
        self.button_4.setObjectName("button_4")
        self.button_3 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("3") )
        self.button_3.setGeometry(QtCore.QRect(190, 270, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_3.setFont(font)
        self.button_3.setObjectName("button_3")
        self.button_subtract = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("-") )
        self.button_subtract.setGeometry(QtCore.QRect(275, 270, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_subtract.setFont(font)
        self.button_subtract.setObjectName("button_subtract")
        self.button_2 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("2") )
        self.button_2.setGeometry(QtCore.QRect(100, 270, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_2.setFont(font)
        self.button_2.setObjectName("button_2")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("1") )
        self.button_1.setGeometry(QtCore.QRect(10, 270, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_1.setFont(font)
        self.button_1.setObjectName("button_1")
        self.button_dot = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it(".") )
        self.button_dot.setGeometry(QtCore.QRect(190, 350, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_dot.setFont(font)
        self.button_dot.setObjectName("button_dot")
        self.button_add = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("+") )
        self.button_add.setGeometry(QtCore.QRect(275, 350, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_add.setFont(font)
        self.button_add.setObjectName("button_add")
        self.button_0 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("0") )
        self.button_0.setGeometry(QtCore.QRect(100, 350, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_0.setFont(font)
        self.button_0.setObjectName("button_0")
        self.button_equal = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("=") )
        self.button_equal.setGeometry(QtCore.QRect(10, 350, 75, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_equal.setFont(font)
        self.button_equal.setObjectName("button_equal")
        self.button_CE = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("CE") )
        self.button_CE.setGeometry(QtCore.QRect(10, 440, 161, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_CE.setFont(font)
        self.button_CE.setObjectName("button_CE")
        self.button_C = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("C") )
        self.button_C.setGeometry(QtCore.QRect(180, 440, 161, 74))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_C.setFont(font)
        self.button_C.setObjectName("button_C")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def press_it(self, pressed):
        if pressed=="C":
            self.outputLabel.setText("0")
        elif pressed=="CE":
            text=self.outputLabel.text()
            self.outputLabel.setText(text[:len(text)-1])
        elif pressed=="=":
            text=self.outputLabel.text()
            try:
                ans=eval(text)
                self.outputLabel.setText(str(ans))
            except:
                self.outputLabel.setText("Wrong Input!")
        else:
            if self.outputLabel.text()=="0":
                self.outputLabel.setText("")
            self.outputLabel.setText(f'{self.outputLabel.text()}{pressed}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_divide.setText(_translate("MainWindow", "/"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_multiply.setText(_translate("MainWindow", "*"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_subtract.setText(_translate("MainWindow", "-"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_dot.setText(_translate("MainWindow", "."))
        self.button_add.setText(_translate("MainWindow", "+"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_equal.setText(_translate("MainWindow", "="))
        self.button_CE.setText(_translate("MainWindow", "CE"))
        self.button_C.setText(_translate("MainWindow", "C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
